### ISSUE TITLE
Scheduling (epic?):   publishing, unpublishing, reverting

### ISSUE THREAD

**Issue by davidsiddall** [localgovdrupal/localgov_core#96]
### User story

**As a:** Product Owner,
**I want:** Scheduling of content to be enabled by default when I enable localgov_workflows
**So that:** Website editors can publish smarter and have their needs met

Please see research on https://github.com/localgovdrupal/localgov/issues/242 

This includes:

- scheduling a new page to go live 
- scheduling a new draft to an existing page to go live
- scheduling content to unpublish
- scheduling a reversion to a previous revision*

### Acceptance tests

See

[Miro board](https://miro.com/app/board/o9J_lHm9M2s=/)

When a user edits a page, they are able to control when it publishes and when it unpublishes to their liking. 

There is an option to complete publish on and unpublish on date and time fields.

Examples:

- I want a piece of content to publish on Friday and remain on the site indefinitely, I should complete the publish on field.
- If I want a piece of content to go live immediately and unpublish at the end of the month, I’d complete the unpublish field.
- If I want content to be live for a specified time in the future, I would complete both the publish on and unpublish on fields.

For Contributors [contributor] who do not have permissions to publish content straight to live, they can still schedule. They send their edit for approval, and the scheduling would be reflected when their edit is approved. Content will never go live before it has been approved.

### Notes on reverting to previous revisions*

This might be done via the revisions tabs. But may need technical discovery

### Tasks

- [x] Enable Drupal scheduler or scheduled transitions module (depending on translations / revisions)
~~- [ ] Configure publish and unpublish date and time fields~~
- [x] Configure permissions for all users
- [x] Ensure scheduling works with workflow
- [x] Write tests.

**Comment by stephen-cox** [comment]
@davidsiddall I have added and configured Scheduled Transitions and confirmed this works with the LocalGov Workflows. This has been deployed to the test site for people to have a play with.

Scheduled Transitions doesn't work in a way that isn't entirely consistent with the description in the user story and acceptance tests so I wanted to check a couple of things.

Content scheduling has it's own tab on the content page rather than fields on the content edit page. We can implement fields on a content edit page that then automatically create entries that appear on the 'Scheduled transitions` page, but this will be quite a bit of extra work. My suggestion is to go with what we have for now - scheduling happens on the Scheduled transitions tab - and add the publish / unpublish fields to content edit pages if testing shows using the tab for scheduling is problematic. Does that sound okay?

The one thing that will be quire difficult to implement is the ability for contributors to schedule content to be published, but only have that go ahead once the content had been approved by an editor. As it stands, they would have to ask the editor to add the scheduling. How big a problem is this? If it's a problem then I'll have to do some investigation in how best to deal with this situation.

**Comment by davidsiddall** [comment]
Hi @stephen-cox I went to test this but can't see it set up on the next site. Are the tabs there yet? This all sounds good in principle. A workaround could be that contributors could request scheduling in the revision log message.

**Comment by stephen-cox** [comment]
Hi @davidsiddall, this is installed on the test site (https://test.localgovdrupal.org/). Once you're logged in you'll see a new tab on the content page called 'Scheduled transitions'; e.g.; https://test.localgovdrupal.org/dave-s-test-title-page, which should take you to https://test.localgovdrupal.org/node/89/scheduled-transitions

**Comment by davidsiddall** [comment]
Thanks @stephen-cox have subsequently tested with the correct user and this is working as expected. I think this is a workable solution and for contributors who want to schedule, they could state it on their revision message as to when they want it to go live.

**Comment by finnlewis** [comment]
@stephen-cox  - ready to merge I think
